export const MESSAGE_LIST_REQUEST = "MESSAGE_LIST_REQUEST" 
export const MESSAGE_LIST_SUCCESS = "MESSAGE_LIST_SUCCESS" 
export const MESSAGE_LIST_FAIL = "MESSAGE_LIST_FAIL"


export const MESSAGE_DETAILS_REQUEST = "MESSAGE_DETAILS_REQUEST" 
export const MESSAGE_DETAILS_SUCCESS = "MESSAGE_DETAILS_SUCCESS" 
export const MESSAGE_DETAILS_FAIL = "MESSAGE_DETAILS_FAIL"